### ISSUE TITLE
复制已有款式&样衣没有跳转提示

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#20]

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63563771-d754c780-c594-11e9-8831-100217d587b4.png)
![image](https://user-images.githubusercontent.com/53415567/63563779-dcb21200-c594-11e9-96b6-375019573154.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63577942-0afa1680-c5c2-11e9-9484-3990e9da09ee.png)
