### ISSUE TITLE
样衣追踪的提示文字要修改

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#21]

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63563803-efc4e200-c594-11e9-848c-9bdeeaeca80e.png)
改成输入【打样追踪记录】

**Comment by QGBZ** [comment]
![updateProduceNoteCase](https://user-images.githubusercontent.com/51871014/63573727-af775b00-c5b8-11e9-905d-b33b55531715.gif)
