### ISSUE TITLE
我的团队

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#22]

**Comment by zack666888** [comment]
我的团队功能要优化一下，被管理员移出小组后，被移除的成员再次进入小程序需要有提示

**Comment by QGBZ** [comment]
考虑到当管理员删除该小组成员时，如果该成员并未打开小程序，该成员看不到的。而当该成员过段时间再次打开小程序时，他的数据会自动刷新成管理员，并且清除之前的样衣信息，建议不做
