### ISSUE TITLE
款式图片和样衣图片的（8/8）没有

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#23]

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63564467-c22d6800-c597-11e9-8e76-5035b04d85dc.png)
![image](https://user-images.githubusercontent.com/53415567/63564470-c48fc200-c597-11e9-906d-2a9766047437.png)

**Comment by QGBZ** [comment]
![addPic](https://user-images.githubusercontent.com/51871014/63583536-c5434b00-c5cd-11e9-82be-5b077e30dfb3.gif)
