### ISSUE TITLE
样衣信息的打样追踪的【新增记录】颜色要换一下

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#24]

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63564489-cfe2ed80-c597-11e9-85ad-8f41d042a098.png)

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63564489-cfe2ed80-c597-11e9-85ad-8f41d042a098.png)


![image](https://user-images.githubusercontent.com/53415567/63570184-d892ee00-c5ae-11e9-8c51-0d818d31b874.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63573693-91a9f600-c5b8-11e9-94ae-17fe59f5316c.png)
