### ISSUE TITLE
样衣信息的款式图片改成样衣图片

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#25]

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63564500-dc674600-c597-11e9-8905-0db55134486a.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63573767-d03fb080-c5b8-11e9-8b27-525565b53978.png)
