### ISSUE TITLE
款式列表的下拉没按照设计稿做

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#26]

**Comment by zack666888** [comment]
款式列表的下拉的效果像设计稿一样，下拉在右侧
虚线的左边和右边应该和设计稿一样，留白
样衣列表和款式中间的缝隙应该填满
![image](https://user-images.githubusercontent.com/53415567/63569059-4e488b00-c5aa-11e9-83b7-3785ae2bb463.png)
![image](https://user-images.githubusercontent.com/53415567/63569073-5ef90100-c5aa-11e9-9f7e-979174fcc9bc.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63573903-21e83b00-c5b9-11e9-9eb1-3e2384e66a82.png)
