### ISSUE TITLE
系列，种类，备注，在设计稿里面没有左边对其

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#27]

**Comment by zack666888** [comment]
要和设计稿一样
![image](https://user-images.githubusercontent.com/53415567/63569106-88199180-c5aa-11e9-8c7e-6e8ca2f2bac4.png)

![image](https://user-images.githubusercontent.com/53415567/63569122-99fb3480-c5aa-11e9-9ba1-8bda6c324b4e.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63574830-4513ea00-c5bb-11e9-8921-2f81aac9d094.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63575157-f9157500-c5bb-11e9-97ff-7365d89a99e9.png)
