### ISSUE TITLE
样衣列表下拉框填写信息的需要有下拉按钮

### ISSUE THREAD

**Issue by zack666888** [yb7/proofing-weapp-issues#28]

**Comment by zack666888** [comment]
![image](https://user-images.githubusercontent.com/53415567/63569265-43dac100-c5ab-11e9-9713-d204a3cca625.png)
![image](https://user-images.githubusercontent.com/53415567/63569278-489f7500-c5ab-11e9-9f6e-b3f3ccf6ead0.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63582597-f3279000-c5cb-11e9-94fb-c34ffbd25f05.png)
