### ISSUE TITLE
样衣图片变成样衣状态后 图片方角

### ISSUE THREAD

**Issue by qukeguo** [yb7/proofing-weapp-issues#30]
样衣图片变成样衣状态后 图片方角 和文字没有对齐下方
![image](https://user-images.githubusercontent.com/54431648/63631777-6a0d6900-c65e-11e9-966b-219a96c669b4.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63633013-d9da1e80-c673-11e9-8243-498eead64a87.png)
你是说这个圆角消失不见了吗？请问是通过什么样的操作导致的这个bug

**Comment by QGBZ** [comment]
上传图片左边有白边，有余背景是白色，导致圆角看不见
