### ISSUE TITLE
款式信息 下拉灰色卡片  上下留白

### ISSUE THREAD

**Issue by qukeguo** [yb7/proofing-weapp-issues#31]
![image](https://user-images.githubusercontent.com/54431648/63631864-68907080-c65f-11e9-9c38-96d3361325df.png)
上下留白 红线部分
![image](https://user-images.githubusercontent.com/54431648/63631872-94135b00-c65f-11e9-89e6-b2b9467557ad.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63632697-f6735800-c66d-11e9-8027-562275c34ff3.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63632984-9da6be00-c673-11e9-9f48-133254e4c017.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63633156-0131eb00-c676-11e9-9022-495e6383c44b.png)
![image](https://user-images.githubusercontent.com/51871014/63633159-098a2600-c676-11e9-9e50-4cd917dd071f.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63633210-12c7c280-c677-11e9-845d-d5ed5d8aca66.png)
