### ISSUE TITLE
款式信息 问题2

### ISSUE THREAD

**Issue by qukeguo** [yb7/proofing-weapp-issues#32]
![image](https://user-images.githubusercontent.com/54431648/63631888-d8066000-c65f-11e9-81ac-4791e808aef5.png)
款式信息 灰色下拉样衣编号写成款号  改下
![image](https://user-images.githubusercontent.com/54431648/63631898-0126f080-c660-11e9-9198-fbf35c408370.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63632096-f588f900-c662-11e9-877b-4b9e62f691d9.png)

**Comment by QGBZ** [comment]
![image](https://user-images.githubusercontent.com/51871014/63632110-181b1200-c663-11e9-93b6-0e7de54fe6c2.png)
